language: ruby

cache:
  bundler: true

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - jruby-19mode
  - ruby-head
  - jruby-head

notifications:
  email: false

sudo: false

branches:
  only:
    - master
    - development

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
